M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue 02 Jun 2026 05:33:45 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-02T17:33:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X19.7Y-168.097
X19.71Y-85.598
X19.71Y-106.223
X19.71Y-127.102
X19.71Y-147.58
X19.71Y-181.5
M30
